// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOrn9d_HBr-EE5NC_1cyCwVt3klxPiPUo',
    appId: '1:50713270266:web:69f60430a4b35c5dc6f643',
    messagingSenderId: '50713270266',
    projectId: 'learnflutter-68b6e',
    authDomain: 'learnflutter-68b6e.firebaseapp.com',
    storageBucket: 'learnflutter-68b6e.appspot.com',
    measurementId: 'G-2JJGJYQBJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYig5e78RDKsnaGAoQMohSidTCRRcjDKI',
    appId: '1:50713270266:android:820351561ba4066cc6f643',
    messagingSenderId: '50713270266',
    projectId: 'learnflutter-68b6e',
    storageBucket: 'learnflutter-68b6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOGx0aanjXQSiDe9A8nkbG2w0AOH7P-HQ',
    appId: '1:50713270266:ios:c77ed28986bb8a24c6f643',
    messagingSenderId: '50713270266',
    projectId: 'learnflutter-68b6e',
    storageBucket: 'learnflutter-68b6e.appspot.com',
    iosBundleId: 'com.example.learnflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOGx0aanjXQSiDe9A8nkbG2w0AOH7P-HQ',
    appId: '1:50713270266:ios:c77ed28986bb8a24c6f643',
    messagingSenderId: '50713270266',
    projectId: 'learnflutter-68b6e',
    storageBucket: 'learnflutter-68b6e.appspot.com',
    iosBundleId: 'com.example.learnflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOrn9d_HBr-EE5NC_1cyCwVt3klxPiPUo',
    appId: '1:50713270266:web:f211b971cc3cc518c6f643',
    messagingSenderId: '50713270266',
    projectId: 'learnflutter-68b6e',
    authDomain: 'learnflutter-68b6e.firebaseapp.com',
    storageBucket: 'learnflutter-68b6e.appspot.com',
    measurementId: 'G-N2XEN4EHXS',
  );
}
